In [1]:
import numpy as np

### **Vector operations**

In [2]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [3]:
u + v

array([3, 4, 5, 8])

In [4]:
u * v

array([ 2,  0,  0, 12])

In [16]:
u - v

array([1, 4, 5, 4])

### **Multiplication**

#### Vector-vector multiplication (dot product)

In [13]:
def vector_vector_mult(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [14]:
vector_vector_mult(u, v)

14.0

In [15]:
u.dot(v)

14

#### Matrix-vector multiplication

In [19]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [22]:
def matrix_vector_mult(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_mult(U[i], v)
    
    return result

In [23]:
matrix_vector_mult(U, v)

array([14.,  5.,  5.])

In [24]:
U.dot(v)

array([14,  5,  5])

#### Matrix-matrix multiplication

In [30]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [31]:
def matrix_matrix_mult(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_mult(U, vi)
        result[:, i] = Uvi

    return result

In [32]:
matrix_matrix_mult(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [33]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### **Identity matrix**

In [40]:
I = np.eye(3)

In [41]:
V.dot(3)

array([[3. , 3. , 6. ],
       [0. , 1.5, 3. ],
       [0. , 6. , 3. ],
       [6. , 3. , 0. ]])

In [42]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### **Inverse**

In [44]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [46]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [47]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])