In [2]:
import numpy as np

### **Creating arrays**

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 4, 5, 7, 12])
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [7]:
a[2]

3

In [8]:
a[3] = 10
a

array([ 1,  2,  3, 10,  5,  7, 12])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

### **Multi-dimensional arrays**

In [11]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [19]:
n[:, 2]

array([3, 6, 1])

In [20]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### **Randomly generated arrays**

In [27]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [28]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [29]:
np.random.seed(2)
100 * np.random.randn(5, 2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [31]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### **Element-wise operations**

In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
a + 1

array([1, 2, 3, 4, 5])

In [34]:
a * 2

array([0, 2, 4, 6, 8])

In [35]:
a * 1000

array([   0, 1000, 2000, 3000, 4000])

In [40]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [41]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [42]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [43]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [44]:
a / b + 100

array([100.        , 100.69444444, 101.02040816, 101.171875  ,
       101.2345679 ])

### **Comparison operations**

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a >= 2

array([False, False,  True,  True,  True])

In [47]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [48]:
a > b

array([False, False,  True,  True,  True])

In [49]:
a[a > b]

array([2, 3, 4])

### **Summarizing operations**

In [51]:
a

array([0, 1, 2, 3, 4])

In [50]:
a.min()

0

In [55]:
a.max()

4

In [52]:
a.sum()

10

In [53]:
a.mean()

2.0

In [54]:
a.std()

1.4142135623730951

In [56]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [57]:
n.sum()

35

In [58]:
n.mean()

3.888888888888889

In [60]:
n.max()

20